### ISSUE TITLE
Consider renaming project

### ISSUE THREAD

**Issue by snicoll** [dabla/grizzly-spring-boot-starter#1]
Thanks for creating the starter! 

I am reaching out to [reference our naming policy](https://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/#boot-features-custom-starter-naming) for third party starter. If possible, could you please rename to comply with it? `grizzly-spring-boot-starter` comes to mind if the Grizzly community is ok with that name.

**Comment by dabla** [comment]
> Thanks for creating the starter!
> 
> I am reaching out to [reference our naming policy](https://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/#boot-features-custom-starter-naming) for third party starter. If possible, could you please rename to comply with it? `grizzly-spring-boot-starter` comes to mind if the Grizzly community is ok with that name.

Hello Stéphane, thank you for pointing this out, I'll adapt the name asap.  Kind regards, David

**Comment by dabla** [comment]
I suppose it's better to create a new github repository named grizzly-spring-boot-starter then base on this one?  What do you propose?  Kind regards, David

**Comment by snicoll** [comment]
Oh no need to and good catch on making sure the github project follows the same name. As a admin you can go to settings and there is an option down there to rename the project. I suggest to do that and redirections will be applied automatically

**Comment by dabla** [comment]
Artifact and github repository have been renamed accordingly + new release has been triggered on sonatype so I expect it to arrive on central maven repository soon.  Do you know if there is any way to remove to original release?  Not that it is of any issue but would be cleaner (and less confusing).

**Comment by snicoll** [comment]
Thank you, very much appreciated.

> Do you know if there is any way to remove to original release? Not that it is of any issue but would be cleaner (and less confusing).

Thanks for caring. I agree it would be less confusing. I'd try by [creating an issue on OSSRH](https://issues.sonatype.org/browse/OSSRH).
